name: chatbot
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.8.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.0.11 # モバイルデバイス向け
  sqflite_common_ffi: ^2.3.0 # ここに追加
  idb_shim: ^2.0.0
  crypto: ^3.0.0
  flutter_stripe: ^11.2.0
  intl: ^0.17.0
  google_sign_in: ^6.1.6
  socket_io_client: ^2.0.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/google_logo.png

android:
  minSdkVersion: 21
